import { createApp } from "vue";
import BaseCard from "./components/ui/BaseCard.vue";
import BaseButton from "./components/ui/BaseButton.vue";
import BaseBadge from "./components/ui/BaseBadge.vue";
import BaseSpinner from "./components/ui/BaseSpinner.vue";
import BaseDialog from "./components/ui/BaseDialog.vue";
import "bootstrap/dist/css/bootstrap.css";
// import bootstrap from "bootstrap/dist/js/bootstrap.bundle.min.js";
import router from "./router";
import store from "./store/index.js";
import { firebaseApp } from "../config/firebaseAuth.ts";
import App from "./App.vue";

const app = createApp(App);
app.config.globalProperties.$firebase = firebaseApp;
app.component("base-card", BaseCard);
app.component("base-button", BaseButton);
app.component("base-badge", BaseBadge);
app.component("base-spinner", BaseSpinner);
app.component("base-dialog", BaseDialog);
app.use(store);
app.use(router).mount("#app");
